
services:
  db-mongo:
  # kéo mongo version 6..
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose: 
      - 27017
      
  be-nest: 
    build:
      # chỉ ra file dockerFile nằm ở đâu
      context: .
      
      dockerfile: Dockerfile
    # restart: unless-stopped 
    # ghì đè
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:123456@localhost:27017/hoidanit?authSource=admin
      # - DB_HOST=host.docker.internal
    expose:
      - 8080
    ports:
      - 8080:8080
volumes:
  mongodb:


  #docker compose -p hoidanit-nest up -d